# Generated by Django 6.0.3 on 2026-04-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='voice_samples',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
